#!/bin/bash

######################################################################
# copyspl0it
# search and copy Exploit from exploit-db 2 metasploit-framework
# Needs searchsploit amd metasploit-framework installed
# script install this tools for you
# First run from github directory ./copyspl0it ... after install 
# use command copyspl0it system wide 
# command: > copyspl0it $searchsting1 $searchstring2 $searchstring3
######################################################################

######################################################################
# create 16.09.2017
# last modify: 16.09.2017
# bug or anything: d43M0n23@3xpl0it.com
######################################################################

######################################################################

# Bash sTyl3!
clear='\033[0m'			#alle Attribute zurücksetzen
red='\e[31m'
bold='\033[1m'			#Fettschrift
underline='\033[4m'		#Unterstreichen
blinken='\033[5m'		#Blinken
invers='\033[7m'		#inverse Darstellung
black='\033[30m'		#Schriftfarbe schwarz
red='\033[31m'			#Schriftfarbe rot
green='\033[32m'		#Schriftfarbe grün
yell='\033[33m'			#Schriftfarbe gelb
blue='\033[34m'			#Schriftfarbe blau
mag='\033[35m'			#Schriftfarbe magenta
turk='\033[36m'			#Schriftfarbe türkis
white='\033[37m'		#Schriftfarbe weiß
orange='\033[93m'		#Schriftfarbe orange
######################################################################


##Variablen
DATE=$(date +%F)
version=1.0
vdate=15.09.2017

# Local Destination
INSTALL_DIR=/usr/share/copyspl0it

# Exploit-db dir
SOURCE_PATH=/usr/share/exploitdb/platforms

# MSF4 - Metasploit user dir
MSF_PATH=$HOME/.msf4/modules/exploits


# Tools install
if ! hash searchsploit 2>/dev/null; then sudo apt-get update && apt-get upgrade -y; sudo apt-get install --yes searchsploit ; fi
if ! hash msfconsole 2>/dev/null; then sudo apt-get update && apt-get upgrade -y; sudo apt-get install --yes metasploit-framework ; fi

#INSTALL
if [ ! -d $INSTALL_DIR ]; then
echo -e "\n${green} + -- --=[Your first run${clear}"
echo -e "${green} + -- --=[This script will install copyspl0it under $INSTALL_DIR.${clear}"
sleep 2
mkdir -p $INSTALL_DIR 2> /dev/null
cp -Rf $PWD/* $INSTALL_DIR 2> /dev/null
rm -f /usr/bin/copyspl0it
ln -s $INSTALL_DIR/copyspl0it /usr/bin/copyspl0it
fi
### FUNCTIONS ###

### START SCRIPT ###
#echo -e '\n'
#echo -e '                                         .__  _______  .__  __   '
#echo -e '  ____  ____ ______ ___.__. ____________ |  | \   _  \ |__|/  |_ '
#echo -e '_/ ___\/  _ \\____ <   |  |/  ___/\____ \|  | /  /_\  \|  \   __\'
#echo -e '\  \__(  <_> )  |_> >___  |\___ \ |  |_> >  |_\  \_/   \  ||  |  '
#echo -e ' \___  >____/|   __// ____/____  >|   __/|____/\_____  /__||__|  '
#echo -e '     \/      |__|   \/         \/ |__|               \/          '
#echo -e "${orange} + -- --=[https://3xpl0it.com${clear} Version ${version}"


clear
echo -e '\n'
echo -e '                                       ______  _ __ '
echo -e '    _________  ____  __  ___________  / / __ \(_) /_'
echo -e '   / ___/ __ \/ __ \/ / / / ___/ __ \/ / / / / / __/'
echo -e '  / /__/ /_/ / /_/ / /_/ (__  ) /_/ / / /_/ / / /_  '
echo -e '  \___/\____/ .___/\__, /____/ .___/_/\____/_/\__/  '
echo -e '           /_/    /____/    /_/                     '
echo -e "\n${orange} + -- --=[https://3xpl0it.com${clear} ${red}Version ${version}${clear}"
sleep 1


echo -e "\n"
cat <<EOF
search the exploit like searchsploit string1 string2 string3.
e.g 'copyspl0it wordpress 4.7.0 inject'
Then specify the number of the exploit found.
EOF

echo -e "\n"
read -p "Exploit (e.g. Wordpress)? " search1 search2 search3
if [ $search1 ]; then
		searchsploit $search1 $search2 $search3

		searchsploit $search1 $search2 $search3 --colour > $INSTALL_DIR/search_tmp
                else
                echo -e "\nPlease enter a searchstring like [wordpress 4.7 content]!\n"
fi
echo -e "\n"
read -p "Please enter the Exploit No.: (e.g. 23234)? " exploitno
if [ $exploitno ]; then
	exploit_path=$(cat $INSTALL_DIR/search_tmp | grep "${exploitno}" | cut -d "|" -f2)
	exploit_dir=$exploit_path
  	exploit_dir="$(dirname $exploit_dir)"
	exploit_file="$(basename $exploit_path)"

if [ ! -d $MSF_PATH/$exploit_dir ]; then mkdir -p $MSF_PATH/$exploit_dir; fi
	cd $SOURCE_PATH/$exploit_dir/
	cp  $exploit_file $MSF_PATH/$exploit_dir/
	echo -e "Your selected exploit was copy to your .msf4 Directory"
	else 
	echo -e "\nPlease enter the exploit number like [33613]!\n"
fi
echo -e "\n${red}"
read -p "Use search by copysploit [A]gain or [E]xit " rerun
echo -e "\n${clear}"
if [ $rerun = A ]; then copyspl0it; fi
exit
